version: "3"

services:
  auth-api-ru:
    command: npm run start:prod
    env_file: /home/cwash/apps/ds-mobile/config/auth/.env.production
    volumes:
      - /home/cwash/apps/ds-mobile/logs/auth:/usr/app/src/logs
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
  core-api:
    command: npm run start:prod
    env_file: /home/cwash/apps/ds-mobile/config/core/.env.production
    volumes:
      - /home/cwash/apps/ds-mobile/logs/core:/usr/app/src/logs
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf.prod:/etc/nginx/conf.d/default.conf
      - /home/cwash/apps/ds-mobile/logs/nginx:/var/log/nginx
      - /home/cwash/apps/certs/ds-mobile.ru.crt:/etc/ssl/ds-mobile.ru.crt
      - /home/cwash/apps/certs/ds-mobile.ru.key:/etc/ssl/ds-mobile.ru.key
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"