version: "3"

services:
  auth-api-ru:
    command: npm run start:prod
    env_file: /home/cwash/apps/ds-mobile/config/auth/.env.production
    volumes:
      - /home/cwash/apps/ds-mobile/logs/auth:/usr/app/src/logs
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
  core-api:
    command: npm run start:prod
    env_file: /home/cwash/apps/ds-mobile/config/core/.env.production
    volumes:
      - /home/cwash/apps/ds-mobile/logs/core:/usr/app/src/logs
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
  ds-mobile-rp:
    container_name: ds-mobile-rp
    hostname: ds-mobile-rp
    ports:
      - "5050:5050"
    volumes:
      - ./nginx/default.conf.prod:/etc/nginx/conf.d/default.conf
      - /home/cwash/apps/ds-mobile/logs/nginx:/var/log/nginx
      - ./public/:/usr/share/nginx/public
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: unless-stopped
networks:
  default:
    external:
      name: ds-mobile-external