version: "3"

services:
  auth-api-ru:
    command: npm run start:dev
    env_file: /Users/eshom/Developer/Mobile/.env/auth/.env.development
    volumes:
      - ./ds-mobile-auth/src/:/usr/app/src
  core-api:
    command: npm run start:dev
    env_file: /Users/eshom/Developer/Mobile/.env/core/.env.development
    volumes:
      - ./ds-mobile-core/src:/usr/app/src
  nginx:
    ports:
      - "5050:80"
    volumes:
      - ./nginx/default.conf.dev:/etc/nginx/conf.d/default.conf